# Generated by Django 5.1.4 on 2025-01-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_title', models.CharField(max_length=200, null=True)),
                ('company_name', models.CharField(max_length=200, null=True)),
                ('location', models.CharField(max_length=70, null=True)),
                ('employment_type', models.CharField(max_length=30, null=True)),
                ('min_salary', models.IntegerField(null=True)),
                ('max_salary', models.IntegerField(null=True)),
                ('link', models.URLField()),
                ('contract_type', models.CharField(blank=True, max_length=100, null=True)),
                ('seniority', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
